
import 'texts.dart';

class AppLanguages {
  static const Map<String, String> en = {
    appTexts.dashboard: "Dashboard",
    appTexts.pendingrequest: "Pending request",
    appTexts.assigndriver: "Assign driver",
    appTexts.availableDriver: "Available Driver",
    appTexts.personalDetails: "Personal Details",
    appTexts.navigate: "Navigate",
    appTexts.notification: "Notifications",
    appTexts.deliveryDetails: "Delivery details",
    appTexts.captionMedicalEquipment: "Medical Equipmenmt for Students",
    appTexts.customerName: "Customer Name",
    appTexts.pickupAddress: "Pickup Address",
    appTexts.deliveryAddress: "Delivery Address",
    appTexts.deliveryDate: "Delivery Date",
    appTexts.deliveryId: "Delivery ID",
    appTexts.productDetails: "Product details",
    appTexts.activity: "Activity",
    appTexts.message: "Message",
    appTexts.inbox: "Inbox",
    appTexts.account: "Account",
    appTexts.name: "Name",
    appTexts.mail: "Mail",
    appTexts.mobile: "Mobile",
    appTexts.address: "Address",
    appTexts.dateOfBirth: "Date of Birth",
    appTexts.nationality: "Nationality",
    appTexts.email: "Email",
    appTexts.paymentMethod: "Payment Method",
    appTexts.setting: "Settings",
    appTexts.accountSettong: "Account setting",
    appTexts.moreOption: "More options",
    appTexts.abouUs: "About Us",
    appTexts.contactSupport: "Contact support",
    appTexts.safetyPolicy: "Safety & Policy",
    appTexts.deliveryJobSupport: "Delivery & Job Support",
    appTexts.appTechnicalHelp: "App & Technical Help",
    appTexts.customerSuppoert: "Customer Support",
    appTexts.requestForTruck: "Request for a Truck",
    appTexts.driverName: "Driver Name",
    appTexts.shipment: "Shipment",
    appTexts.subscriptionPlan: "Subscriptions Plans",
    appTexts.signUp: "Sign up",
    appTexts.companyName: "Comapny Name",
    appTexts.companyMail: "Comapny Mail",
    appTexts.companyLogo: "Comapny logo",
    appTexts.uniqueCode: "Unique code",
    appTexts.password: "Password",
    appTexts.confirmPassword: "Confirm Password",
    appTexts.sparkDelivery: "Spark delivery",
    appTexts.addDriver: "Add Driver",
    appTexts.addDispatcher: "Add Dispatcher",
    appTexts.driverDetails: "Driver details",
    appTexts.onboardingTitle1: "Discover Barbershops Near You",
    appTexts.onboardingDesc1: "Find the best barbershops around you – with real reviews to help you choose the perfect cut and the right barber. Discover barbers who match your style, budget and preferences.",
    appTexts.onboardingTitle2: "Join the Online Beard Contest",
    appTexts.onboardingDesc2: "Show off your beard in our exclusive community, join the online contest, and win awesome prizes. Hall of Fame included!",
    appTexts.onboardingTitle3: "Collect Exclusive Beardcoins",
    appTexts.onboardingDesc3: "Earn digital stamps – our Beardcoins! Collect loyalty points and unlock special perks for true beard lovers.",
    appTexts.onboardingTitle4: "Boost Your Shop's Visibility",
    appTexts.onboardingDesc4: "Barber owners register your shop, showcase key info, and get discovered – all without needing your own website.",
    appTexts.onboardingTitle5: "100% Digital, Zero Paper",
    appTexts.onboardingDesc5: "No more printed stamp cards. Award digital rewards, set your own discounts, and surprise customers smarter than ever.",
    appTexts.skip: "Skip",
    appTexts.next: "Next",
    appTexts.tellUsAboutYourself: "Tell Us About Yourself",
    appTexts.chooseToContinue: "Choose to Continue",
    appTexts.beardfriend: "Beardfriend",
    appTexts.beardfriendDesc: "(For members only)",
    appTexts.barbershop: "Barbershop",
    appTexts.barbershopDesc: "(For owners only)",
    appTexts.cookieSettings: "Cookies Setting",
    appTexts.cookiePolicy: "We use Cookies and similar technologies to help personalize content, tailor and measure ads, and provide a better experience. By clicking accept, you agree to this, as outlined in our ",
    appTexts.cookiePolicyLink: "Cookie Policy",
    appTexts.onlyEssentials: "Only essentials",
    appTexts.changeCookieSettings: "Change cookie settings",
    appTexts.acceptAll: "Accept all",
    appTexts.createAccount: "Create Account",
    appTexts.pleaseSignup: "Please Signup to your Account",
    appTexts.username: "Username",
    appTexts.emailAddress: "Email Address",
    appTexts.dob: "DD/MM/YYYY",
    appTexts.confirmPass: "Confirm Password",
    appTexts.alreadyHaveAccount: "Already have an Account? ",
    appTexts.login: "Login",
    appTexts.gdprTerms: "GDPR and General Terms & Conditions",
    appTexts.agreePrivacyPolicy: "I Agree & Accept ",
    appTexts.privacyPolicy: "Privacy Policy",
    appTexts.agreeTerms: "I Agree & Accept ",
    appTexts.generalTerms: "General Terms & Conditions",
    appTexts.termsHelper: "Make Sure you have read our Terms & Condition before Continue to the app",
    appTexts.continueText: "Continue",
    appTexts.otp: "OTP",
    appTexts.otpSent: "We have sent the verification code to your\nemail address",
    appTexts.didntGetCode: "Didn't get the code? ",
    appTexts.resendIt: "Resend it",
    appTexts.forgotPassword: "Forgot Password?",
    appTexts.typeEmailAddress: "Please Type in your Email Address",
    appTexts.resetPassword: "Reset Password",
    appTexts.rememberPassword: "Remember Password? ",
    appTexts.newPassword: "New Password",
    appTexts.confirmPasswordText: "Confirm Password",
    appTexts.accountCreatedSuccess: "Account created successfully!",
    appTexts.passwordResetSuccess: "Password reset successfully!",
    appTexts.error: "Error",
    appTexts.pleaseEnterName: "Please enter your name",
    appTexts.pleaseEnterEmail: "Please enter your email",
    appTexts.pleaseEnterPassword: "Please enter your password",
    appTexts.pleaseConfirmPassword: "Please confirm your password",
    appTexts.passwordsDoNotMatch: "Passwords do not match",
    appTexts.agreeToTerms: "Please agree to terms and conditions",
    appTexts.countryCode: "Country Code",
    appTexts.rememberMe: "Remember me",
    appTexts.signIn: "Sign in",
    appTexts.fillRequiredFields: "Please make sure to fill in all required (",
    appTexts.fieldsAccurately: ") fields \naccurately",
    appTexts.welcomeBack: "Welcome Back!",
    appTexts.pleaseLogin: "Please Login to your Account",
    appTexts.orContinueWith: "or Continue With",
    appTexts.dontHaveAccount: "Not have an Account? ",
    appTexts.createOne: "Create One",
    appTexts.avatarUpdatedSuccess: "Avatar updated successfully",
    appTexts.avatarUploadFailed: "Failed to upload avatar",
    appTexts.congratulation: "Congratulation!!!",
    appTexts.gotNextBeardCoin: "You have Got a Next Beard Coin!",
    appTexts.coinsCollectionAt: "Your Coins Collection at ",
    appTexts.okGotIt: "Ok, I got it!",
    appTexts.retry: "Retry",
    appTexts.welcome: "Welcome",
    appTexts.scanQrCode: "Let's Scan your QR Code to get a Beard Coin",
    appTexts.personalId: "This is your personal ID.",
    appTexts.scanQrInstruction: "Have your personal QR code scanned by your barber of choice on your next visit and you will immediately receive a digital stamp.",
    appTexts.beardCoinName: "We call it \"beard coin\".",
    appTexts.beardCoins: "Beard Coins",
    appTexts.barbershops: "Barbershops",
    appTexts.shopping: "Shopping",
    appTexts.profile: "Profile",
    appTexts.justNow: "Just now",
    appTexts.mAgo: "m ago",
    appTexts.hAgo: "h ago",
    appTexts.dAgo: "d ago",
    appTexts.notifications: "Notifications",
    appTexts.markAsRead: "Mark As Read",
    appTexts.noNotificationsYet: "No notifications yet",
    appTexts.noMoreNotifications: "No more notifications",
    appTexts.newText: "New",
    appTexts.earlier: "Earlier",
    appTexts.clickHereToParticipate: "Click here to participate",
    appTexts.gift: "Gift",
    appTexts.openingGiftDetails: "Opening gift details...",
    appTexts.contest: "Contest",
    appTexts.openingContestDetails: "Opening contest details...",
    appTexts.reservation: "Reservation",
    appTexts.openingReservationDetails: "Opening reservation details...",
    appTexts.shareThisProfileVia: "Share this profile via",
    appTexts.linkCopiedToClipboard: "Link copied to clipboard",
    appTexts.copy: "Copy",
    appTexts.sharingTo: "Sharing to",
    appTexts.hallOfFame: "Hall of Fame",
    appTexts.currentContest: "Current Contest",
    appTexts.previousWinners: "Previous winners",
    appTexts.loading: "Loading...",
    appTexts.failedToLoadData: "Failed to load data",
    appTexts.noParticipantsYet: "No participants yet",
    appTexts.beFirstToJoin: "Be the first to join the contest!",
    appTexts.votes: "Votes",
    appTexts.totalVotes: "Total Votes",
    appTexts.noPreviousContests: "No previous contests yet",
    appTexts.noWinnersYet: "No winners yet",
    appTexts.failedToLoadContest: "Failed to load contest",
    appTexts.beardContest: "Beard Contest",
    appTexts.participateInContest: "Participate in the Contest",
    appTexts.contestEndsIn: "Contest Ends in",
    appTexts.viewAll: "View All",
    appTexts.leaderBoard: "Leader Board",
    appTexts.takeChanceToJoin: "Take the chance and be the first to join.",
    appTexts.youAlreadyHave: "You already have",
    appTexts.editPhoto: "Edit Photo",
    appTexts.deletePhoto: "Delete Photo",
    appTexts.changeDeletePhoto: "Change/delete photo",
    appTexts.importantNote: "Important Note:",
    appTexts.changePhotoNote: "If you want to change your photo or stop taking part in the contest, you can use this page.",
    appTexts.deletePhotoNote: "After deleting your photo, you can upload a new one. Otherwise, you will be disqualified from the contest.",
    appTexts.cancel: "Cancel",
    appTexts.delete: "Delete",
    appTexts.contestDetails: "Contest Details",
    appTexts.failedToLoadDetails: "Failed to load details",
    appTexts.participants: "Participants",
    appTexts.days: "Days",
    appTexts.hours: "Hours",
    appTexts.mins: "Mins",
    appTexts.personalInfo: "Personal Info",
    appTexts.myReservations: "My Reservations",
    appTexts.privacySecurity: "Privacy & Security",
    appTexts.accountSettings: "Account Settings",
    appTexts.helpSupport: "Help & Support",
    appTexts.logout: "Logout",
    appTexts.all: "All",
    appTexts.pending: "Pending",
    appTexts.confirmed: "Confirmed",
    appTexts.failedToLoadReservations: "Failed to load reservations",
    appTexts.noReservationsFound: "No reservations found",
    appTexts.withBarber: "with",
    appTexts.noDetailsFound: "No details found",
    appTexts.yourCollection: "Your Collection",
    appTexts.aboutUs: "About us",
    appTexts.noDescriptionAvailable: "No description available.",
    appTexts.reviews: "Reviews",
    appTexts.noReviewsYet: "No reviews yet",
    appTexts.howToFindUs: "How to find us",
    appTexts.barbershopDetails: "Barbershop Details",
    appTexts.staff: "Staff:",
    appTexts.languages: "Languages:",
    appTexts.payments: "Payments:",
    appTexts.priceList: "Price List",
    appTexts.noServicesListed: "No services listed",
    appTexts.openingHours: "Opening hours",
    appTexts.noOpeningHoursListed: "No opening hours listed",
    appTexts.portfolio: "Portfolio",
    appTexts.seeAll: "See All",
    appTexts.members: "Members",
    appTexts.closed: "Closed",
    appTexts.editProfile: "Edit Profile",
    appTexts.editYourProfile: "Edit Your Profile",
    appTexts.profilePicture: "Profile Picture",
    appTexts.chooseProfilePicture: "Choose Profile Picture",
    appTexts.takePhoto: "Take Photo",
    appTexts.chooseFromGallery: "Choose from Gallery",
    appTexts.tapToChangeProfilePicture: "Tap to Change your Profile Picture.",
    appTexts.phoneNumber: "Phone Number",
    appTexts.update: "Update",
    appTexts.accountUpdated: "Account Updated",
    appTexts.manageYourAccount: "Manage Your Account",
    appTexts.changeLanguage: "Change Language",
    appTexts.deleteAccount: "Delete Account",
    appTexts.deleteAccountQuestion: "Delete Account?",
    appTexts.deleteAccountConfirmation: "Are you Sure You Want to Confirm Delete your Account? You can not Recover it Once it got deleted. To Confirm Please Type in Confirm.",
    appTexts.typeConfirmHere: "Type \"Confirm\" here",
    appTexts.accountDeleted: "Account Deleted",
    appTexts.accountDeletedSuccess: "Your account has been successfully deleted",
    appTexts.pleaseTypeConfirm: "Please type \"Confirm\" to delete your account",
    appTexts.giveFeedback: "Give Feedback",
    appTexts.howDidWeDo: "How did we do?",
    appTexts.writeReview: "Write a Review",
    appTexts.discard: "Discard",
    appTexts.add: "Add",
    appTexts.success: "Success",
    appTexts.reviewAddedSuccess: "Review added successfully",
    appTexts.reviewsFor: "Reviews for",
    appTexts.customersFeedbackFor: "Customers Feedback for",
    appTexts.addReview: "Add Review",
    appTexts.ago: "ago",
  };

  static const Map<String, String> es = {
    appTexts.dashboard: "Tablero",
    appTexts.pendingrequest: "Solicitud pendiente",
    appTexts.assigndriver: "Asignar conductor",
    appTexts.availableDriver: "Conductor disponible",
    appTexts.personalDetails: "Detalles personales",
    appTexts.navigate: "Navegar",
    appTexts.notification: "Notificaciones",
    appTexts.deliveryDetails: "Detalles de entrega",
    appTexts.captionMedicalEquipment: "Equipo médico para estudiantes",
    appTexts.customerName: "Nombre del cliente",
    appTexts.pickupAddress: "Dirección de recogida",
    appTexts.deliveryAddress: "Dirección de entrega",
    appTexts.deliveryDate: "Fecha de entrega",
    appTexts.deliveryId: "ID de entrega",
    appTexts.productDetails: "Detalles del producto",
    appTexts.activity: "Actividad",
    appTexts.message: "Mensaje",
    appTexts.inbox: "Bandeja de entrada",
    appTexts.account: "Cuenta",
    appTexts.name: "Nombre",
    appTexts.mail: "Correo",
    appTexts.mobile: "Móvil",
    appTexts.address: "Dirección",
    appTexts.dateOfBirth: "Fecha de nacimiento",
    appTexts.nationality: "Nacionalidad",
    appTexts.email: "Correo electrónico",
    appTexts.paymentMethod: "Método de pago",
    appTexts.setting: "Configuración",
    appTexts.accountSettong: "Configuración de cuenta",
    appTexts.moreOption: "Más opciones",
    appTexts.abouUs: "Sobre nosotros",
    appTexts.contactSupport: "Soporte de contacto",
    appTexts.safetyPolicy: "Seguridad y política",
    appTexts.deliveryJobSupport: "Soporte de entrega y trabajo",
    appTexts.appTechnicalHelp: "Ayuda técnica de la aplicación",
    appTexts.customerSuppoert: "Atención al cliente",
    appTexts.requestForTruck: "Solicitud de camión",
    appTexts.driverName: "Nombre del conductor",
    appTexts.shipment: "Envío",
    appTexts.subscriptionPlan: "Planes de suscripción",
    appTexts.signUp: "Registrarse",
    appTexts.companyName: "Nombre de la empresa",
    appTexts.companyMail: "Correo de la empresa",
    appTexts.companyLogo: "Logotipo de la empresa",
    appTexts.uniqueCode: "Código único",
    appTexts.password: "Contraseña",
    appTexts.confirmPassword: "Confirmar contraseña",
    appTexts.sparkDelivery: "Entrega Spark",
    appTexts.addDriver: "Agregar conductor",
    appTexts.addDispatcher: "Agregar despachador",
    appTexts.driverDetails: "Detalles del conductor",
    appTexts.onboardingTitle1: "Descubre barberías cerca de ti",
    appTexts.onboardingDesc1: "Encuentra las mejores barberías a tu alrededor – con reseñas reales para ayudarte a elegir el corte perfecto y el barbero adecuado. Descubre barberos que coincidan con tu estilo, presupuesto y preferencias.",
    appTexts.onboardingTitle2: "Únete al concurso de barba en línea",
    appTexts.onboardingDesc2: "Presume tu barba en nuestra comunidad exclusiva, únete al concurso en línea y gana premios increíbles. ¡Salón de la Fama incluido!",
    appTexts.onboardingTitle3: "Colecciona Beardcoins exclusivas",
    appTexts.onboardingDesc3: "Gana sellos digitales – ¡nuestras Beardcoins! Colecciona puntos de fidelidad y desbloquea beneficios especiales para los verdaderos amantes de la barba.",
    appTexts.onboardingTitle4: "Aumenta la visibilidad de tu tienda",
    appTexts.onboardingDesc4: "Propietarios de barberías registran su tienda, muestran información clave y son descubiertos – todo sin necesidad de su propio sitio web.",
    appTexts.onboardingTitle5: "100% Digital, Cero Papel",
    appTexts.onboardingDesc5: "No más tarjetas de sellos impresas. Otorga recompensas digitales, establece tus propios descuentos y sorprende a los clientes de manera más inteligente que nunca.",
    appTexts.skip: "Omitir",
    appTexts.next: "Siguiente",
    appTexts.tellUsAboutYourself: "Cuéntanos sobre ti",
    appTexts.chooseToContinue: "Elige para continuar",
    appTexts.beardfriend: "Amigo de la barba",
    appTexts.beardfriendDesc: "(Solo para miembros)",
    appTexts.barbershop: "Barbería",
    appTexts.barbershopDesc: "(Solo para propietarios)",
    appTexts.cookieSettings: "Configuración de cookies",
    appTexts.cookiePolicy: "Utilizamos cookies y tecnologías similares para ayudar a personalizar el contenido, adaptar y medir los anuncios y brindar una mejor experiencia. Al hacer clic en aceptar, acepta esto, como se describe en nuestra ",
    appTexts.cookiePolicyLink: "Política de cookies",
    appTexts.onlyEssentials: "Solo esenciales",
    appTexts.changeCookieSettings: "Cambiar configuración de cookies",
    appTexts.acceptAll: "Aceptar todo",
    appTexts.createAccount: "Crear cuenta",
    appTexts.pleaseSignup: "Por favor regístrate en tu cuenta",
    appTexts.username: "Nombre de usuario",
    appTexts.emailAddress: "Dirección de correo electrónico",
    appTexts.dob: "DD/MM/AAAA",
    appTexts.confirmPass: "Confirmar contraseña",
    appTexts.alreadyHaveAccount: "¿Ya tienes una cuenta? ",
    appTexts.login: "Iniciar sesión",
    appTexts.gdprTerms: "RGPD y Términos y Condiciones Generales",
    appTexts.agreePrivacyPolicy: "Acepto ",
    appTexts.privacyPolicy: "Política de privacidad",
    appTexts.agreeTerms: "Acepto ",
    appTexts.generalTerms: "Términos y Condiciones Generales",
    appTexts.termsHelper: "Asegúrate de haber leído nuestros Términos y Condiciones antes de continuar en la aplicación",
    appTexts.continueText: "Continuar",
    appTexts.otp: "OTP",
    appTexts.otpSent: "Hemos enviado el código de verificación a tu\ndirección de correo electrónico",
    appTexts.didntGetCode: "¿No recibiste el código? ",
    appTexts.resendIt: "Reenviarlo",
    appTexts.forgotPassword: "¿Olvidaste tu contraseña?",
    appTexts.typeEmailAddress: "Por favor escribe tu dirección de correo electrónico",
    appTexts.resetPassword: "Restablecer contraseña",
    appTexts.rememberPassword: "¿Recordar contraseña? ",
    appTexts.newPassword: "Nueva contraseña",
    appTexts.confirmPasswordText: "Confirmar contraseña",
    appTexts.accountCreatedSuccess: "¡Cuenta creada exitosamente!",
    appTexts.passwordResetSuccess: "¡Contraseña restablecida exitosamente!",
    appTexts.error: "Error",
    appTexts.pleaseEnterName: "Por favor ingrese su nombre",
    appTexts.pleaseEnterEmail: "Por favor ingrese su correo electrónico",
    appTexts.pleaseEnterPassword: "Por favor ingrese su contraseña",
    appTexts.pleaseConfirmPassword: "Por favor confirme su contraseña",
    appTexts.passwordsDoNotMatch: "Las contraseñas no coinciden",
    appTexts.agreeToTerms: "Por favor acepte los términos y condiciones",
    appTexts.countryCode: "Código de país",
    appTexts.rememberMe: "Recuérdame",
    appTexts.signIn: "Iniciar sesión",
    appTexts.fillRequiredFields: "Asegúrese de completar todos los campos obligatorios (",
    appTexts.fieldsAccurately: ") \ncon precisión",
    appTexts.welcomeBack: "¡Bienvenido de nuevo!",
    appTexts.pleaseLogin: "Por favor inicie sesión en su cuenta",
    appTexts.orContinueWith: "o continuar con",
    appTexts.dontHaveAccount: "¿No tienes una cuenta? ",
    appTexts.createOne: "Crear una",
    appTexts.avatarUpdatedSuccess: "Avatar actualizado exitosamente",
    appTexts.avatarUploadFailed: "Error al subir avatar",
    appTexts.congratulation: "¡¡¡Felicidades!!!",
    appTexts.gotNextBeardCoin: "¡Has conseguido una nueva moneda de barba!",
    appTexts.coinsCollectionAt: "Tu colección de monedas en ",
    appTexts.okGotIt: "¡Ok, lo tengo!",
    appTexts.retry: "Reintentar",
    appTexts.welcome: "Bienvenido",
    appTexts.scanQrCode: "Escanea tu código QR para obtener una moneda de barba",
    appTexts.personalId: "Este es tu ID personal.",
    appTexts.scanQrInstruction: "Haz escanear tu código QR personal por tu barbero de elección en tu próxima visita e inmediatamente recibirás un sello digital.",
    appTexts.beardCoinName: "Lo llamamos \"moneda de barba\".",
    appTexts.beardCoins: "Monedas de Barba",
    appTexts.barbershops: "Barberías",
    appTexts.shopping: "Compras",
    appTexts.profile: "Perfil",
    appTexts.justNow: "Justo ahora",
    appTexts.mAgo: "m hace",
    appTexts.hAgo: "h hace",
    appTexts.dAgo: "d hace",
    appTexts.notifications: "Notificaciones",
    appTexts.markAsRead: "Marcar como leído",
    appTexts.noNotificationsYet: "Aún no hay notificaciones",
    appTexts.noMoreNotifications: "No hay más notificaciones",
    appTexts.newText: "Nuevo",
    appTexts.earlier: "Anterior",
    appTexts.clickHereToParticipate: "Haga clic aquí para participar",
    appTexts.gift: "Regalo",
    appTexts.openingGiftDetails: "Abriendo detalles del regalo...",
    appTexts.contest: "Concurso",
    appTexts.openingContestDetails: "Abriendo detalles del concurso...",
    appTexts.reservation: "Reserva",
    appTexts.openingReservationDetails: "Abriendo detalles de la reserva...",
    appTexts.shareThisProfileVia: "Compartir este perfil vía",
    appTexts.linkCopiedToClipboard: "Enlace copiado al portapapeles",
    appTexts.copy: "Copiar",
    appTexts.sharingTo: "Compartiendo en",
    appTexts.hallOfFame: "Salón de la Fama",
    appTexts.currentContest: "Concurso Actual",
    appTexts.previousWinners: "Ganadores anteriores",
    appTexts.loading: "Cargando...",
    appTexts.failedToLoadData: "Error al cargar datos",
    appTexts.noParticipantsYet: "Aún no hay participantes",
    appTexts.beFirstToJoin: "¡Sé el primero en unirte al concurso!",
    appTexts.votes: "Votos",
    appTexts.totalVotes: "Total de Votos",
    appTexts.noPreviousContests: "No hay concursos anteriores aún",
    appTexts.noWinnersYet: "Aún no hay ganadores",
    appTexts.failedToLoadContest: "Error al cargar concurso",
    appTexts.beardContest: "Concurso de Barba",
    appTexts.participateInContest: "Participar en el Concurso",
    appTexts.contestEndsIn: "El concurso termina en",
    appTexts.viewAll: "Ver Todo",
    appTexts.leaderBoard: "Tabla de Clasificación",
    appTexts.takeChanceToJoin: "Aprovecha la oportunidad y sé el primero en unirte.",
    appTexts.youAlreadyHave: "Ya tienes",
    appTexts.editPhoto: "Editar Foto",
    appTexts.deletePhoto: "Eliminar Foto",
    appTexts.changeDeletePhoto: "Cambiar/eliminar foto",
    appTexts.importantNote: "Nota Importante:",
    appTexts.changePhotoNote: "Si deseas cambiar tu foto o dejar de participar en el concurso, puedes usar esta página.",
    appTexts.deletePhotoNote: "Después de eliminar tu foto, puedes subir una nueva. De lo contrario, serás descalificado del concurso.",
    appTexts.cancel: "Cancelar",
    appTexts.delete: "Eliminar",
    appTexts.contestDetails: "Detalles del Concurso",
    appTexts.failedToLoadDetails: "Error al cargar detalles",
    appTexts.participants: "Participantes",
    appTexts.days: "Días",
    appTexts.hours: "Horas",
    appTexts.mins: "Mins",
    appTexts.personalInfo: "Información Personal",
    appTexts.myReservations: "Mis Reservas",
    appTexts.privacySecurity: "Privacidad y Seguridad",
    appTexts.accountSettings: "Configuración de Cuenta",
    appTexts.helpSupport: "Ayuda y Soporte",
    appTexts.logout: "Cerrar Sesión",
    appTexts.all: "Todo",
    appTexts.pending: "Pendiente",
    appTexts.confirmed: "Confirmado",
    appTexts.failedToLoadReservations: "Error al cargar reservas",
    appTexts.noReservationsFound: "No se encontraron reservas",
    appTexts.withBarber: "con",
    appTexts.noDetailsFound: "No se encontraron detalles",
    appTexts.yourCollection: "Tu Colección",
    appTexts.aboutUs: "Sobre nosotros",
    appTexts.noDescriptionAvailable: "No hay descripción disponible.",
    appTexts.reviews: "Reseñas",
    appTexts.noReviewsYet: "Aún no hay reseñas",
    appTexts.howToFindUs: "Cómo encontrarnos",
    appTexts.barbershopDetails: "Detalles de la Barbería",
    appTexts.staff: "Personal:",
    appTexts.languages: "Idiomas:",
    appTexts.payments: "Pagos:",
    appTexts.priceList: "Lista de Precios",
    appTexts.noServicesListed: "No hay servicios listados",
    appTexts.openingHours: "Horario de Apertura",
    appTexts.noOpeningHoursListed: "No hay horario listado",
    appTexts.portfolio: "Portafolio",
    appTexts.seeAll: "Ver Todo",
    appTexts.members: "Miembros",
    appTexts.closed: "Cerrado",
    appTexts.editProfile: "Editar Perfil",
    appTexts.editYourProfile: "Edita tu Perfil",
    appTexts.profilePicture: "Foto de Perfil",
    appTexts.chooseProfilePicture: "Elegir Foto de Perfil",
    appTexts.takePhoto: "Tomar Foto",
    appTexts.chooseFromGallery: "Elegir de Galería",
    appTexts.tapToChangeProfilePicture: "Toca para cambiar tu foto de perfil.",
    appTexts.phoneNumber: "Número de Teléfono",
    appTexts.update: "Actualizar",
    appTexts.accountUpdated: "Cuenta Actualizada",
    appTexts.manageYourAccount: "Gestionar tu Cuenta",
    appTexts.changeLanguage: "Cambiar Idioma",
    appTexts.deleteAccount: "Eliminar Cuenta",
    appTexts.deleteAccountQuestion: "¿Eliminar Cuenta?",
    appTexts.deleteAccountConfirmation: "¿Estás seguro de que deseas eliminar tu cuenta? No podrás recuperarla una vez eliminada. Para confirmar, escribe Confirmar.",
    appTexts.typeConfirmHere: "Escribe \"Confirmar\" aquí",
    appTexts.accountDeleted: "Cuenta Eliminada",
    appTexts.accountDeletedSuccess: "Tu cuenta ha sido eliminada exitosamente",
    appTexts.pleaseTypeConfirm: "Por favor escribe \"Confirmar\" para eliminar tu cuenta",
    appTexts.giveFeedback: "Dar Feedback",
    appTexts.howDidWeDo: "¿Cómo lo hicimos?",
    appTexts.writeReview: "Escribir una Reseña",
    appTexts.discard: "Descartar",
    appTexts.add: "Agregar",
    appTexts.success: "Éxito",
    appTexts.reviewAddedSuccess: "Reseña agregada exitosamente",
    appTexts.reviewsFor: "Reseñas de",
    appTexts.customersFeedbackFor: "Opiniones de clientes para",
    appTexts.addReview: "Agregar Reseña",
    appTexts.ago: "atrás",
  };

  static const Map<String, String> it = {
    appTexts.dashboard: "Cruscotto",
    appTexts.pendingrequest: "Richiesta in attesa",
    appTexts.assigndriver: "Assegna autista",
    appTexts.availableDriver: "Autista disponibile",
    appTexts.personalDetails: "Dettagli personali",
    appTexts.navigate: "Naviga",
    appTexts.notification: "Notifiche",
    appTexts.deliveryDetails: "Dettagli consegna",
    appTexts.captionMedicalEquipment: "Attrezzature mediche per studenti",
    appTexts.customerName: "Nome cliente",
    appTexts.pickupAddress: "Indirizzo ritiro",
    appTexts.deliveryAddress: "Indirizzo consegna",
    appTexts.deliveryDate: "Data consegna",
    appTexts.deliveryId: "ID consegna",
    appTexts.productDetails: "Dettagli prodotto",
    appTexts.activity: "Attività",
    appTexts.message: "Messaggio",
    appTexts.inbox: "Posta in arrivo",
    appTexts.account: "Account",
    appTexts.name: "Nome",
    appTexts.mail: "Posta",
    appTexts.mobile: "Cellulare",
    appTexts.address: "Indirizzo",
    appTexts.dateOfBirth: "Data di nascita",
    appTexts.nationality: "Nazionalità",
    appTexts.email: "Email",
    appTexts.paymentMethod: "Metodo di pagamento",
    appTexts.setting: "Impostazioni",
    appTexts.accountSettong: "Impostazioni account",
    appTexts.moreOption: "Altre opzioni",
    appTexts.abouUs: "Chi siamo",
    appTexts.contactSupport: "Contatta supporto",
    appTexts.safetyPolicy: "Sicurezza e Politica",
    appTexts.deliveryJobSupport: "Supporto Consegna e Lavoro",
    appTexts.appTechnicalHelp: "Aiuto App e Tecnico",
    appTexts.customerSuppoert: "Servizio Clienti",
    appTexts.requestForTruck: "Richiesta camion",
    appTexts.driverName: "Nome autista",
    appTexts.shipment: "Spedizione",
    appTexts.subscriptionPlan: "Piani di abbonamento",
    appTexts.signUp: "Iscriviti",
    appTexts.companyName: "Nome azienda",
    appTexts.companyMail: "Email azienda",
    appTexts.companyLogo: "Logo azienda",
    appTexts.uniqueCode: "Codice univoco",
    appTexts.password: "Password",
    appTexts.confirmPassword: "Conferma password",
    appTexts.sparkDelivery: "Consegna Spark",
    appTexts.addDriver: "Aggiungi autista",
    appTexts.addDispatcher: "Aggiungi dispatcher",
    appTexts.driverDetails: "Dettagli autista",
    appTexts.onboardingTitle1: "Scopri i barbieri vicino a te",
    appTexts.onboardingDesc1: "Trova i migliori barbieri intorno a te – con recensioni reali per aiutarti a scegliere il taglio perfetto e il barbiere giusto. Scopri barbieri che corrispondono al tuo stile, budget e preferenze.",
    appTexts.onboardingTitle2: "Partecipa al concorso barba online",
    appTexts.onboardingDesc2: "Mostra la tua barba nella nostra comunità esclusiva, partecipa al concorso online e vinci premi fantastici. Hall of Fame inclusa!",
    appTexts.onboardingTitle3: "Colleziona Beardcoins esclusivi",
    appTexts.onboardingDesc3: "Guadagna timbri digitali – i nostri Beardcoins! Raccogli punti fedeltà e sblocca vantaggi speciali per veri amanti della barba.",
    appTexts.onboardingTitle4: "Aumenta la visibilità del tuo negozio",
    appTexts.onboardingDesc4: "I proprietari di barbieri registrano il loro negozio, mostrano informazioni chiave e vengono scoperti – tutto senza bisogno del proprio sito web.",
    appTexts.onboardingTitle5: "100% Digitale, Zero Carta",
    appTexts.onboardingDesc5: "Niente più schede timbri stampate. Assegna premi digitali, imposta i tuoi sconti e sorprendi i clienti in modo più intelligente che mai.",
    appTexts.skip: "Salta",
    appTexts.next: "Avanti",
    appTexts.tellUsAboutYourself: "Raccontaci di te",
    appTexts.chooseToContinue: "Scegli per continuare",
    appTexts.beardfriend: "Amico della barba",
    appTexts.beardfriendDesc: "(Solo per membri)",
    appTexts.barbershop: "Barbiere",
    appTexts.barbershopDesc: "(Solo per proprietari)",
    appTexts.cookieSettings: "Impostazioni cookie",
    appTexts.cookiePolicy: "Utilizziamo cookie e tecnologie simili per aiutare a personalizzare i contenuti, adattare e misurare gli annunci e fornire un'esperienza migliore. Cliccando su accetta, accetti questo, come descritto nella nostra ",
    appTexts.cookiePolicyLink: "Politica sui cookie",
    appTexts.onlyEssentials: "Solo essenziali",
    appTexts.changeCookieSettings: "Modifica impostazioni cookie",
    appTexts.acceptAll: "Accetta tutto",
    appTexts.createAccount: "Crea account",
    appTexts.pleaseSignup: "Per favore iscriviti al tuo account",
    appTexts.username: "Nome utente",
    appTexts.emailAddress: "Indirizzo email",
    appTexts.dob: "GG/MM/AAAA",
    appTexts.confirmPass: "Conferma password",
    appTexts.alreadyHaveAccount: "Hai già un account? ",
    appTexts.login: "Accedi",
    appTexts.gdprTerms: "GDPR e Termini e Condizioni Generali",
    appTexts.agreePrivacyPolicy: "Accetto ",
    appTexts.privacyPolicy: "Politica sulla riservatezza",
    appTexts.agreeTerms: "Accetto ",
    appTexts.generalTerms: "Termini e Condizioni Generali",
    appTexts.termsHelper: "Assicurati di aver letto i nostri Termini e Condizioni prima di continuare nell'app",
    appTexts.continueText: "Continua",
    appTexts.otp: "OTP",
    appTexts.otpSent: "Abbiamo inviato il codice di verifica al tuo\nindirizzo email",
    appTexts.didntGetCode: "Non hai ricevuto il codice? ",
    appTexts.resendIt: "Invialo di nuovo",
    appTexts.forgotPassword: "Hai dimenticato la password?",
    appTexts.typeEmailAddress: "Per favora digita il tuo indirizzo email",
    appTexts.resetPassword: "Reimposta password",
    appTexts.rememberPassword: "Ricordi la password? ",
    appTexts.newPassword: "Nuova password",
    appTexts.confirmPasswordText: "Conferma password",
    appTexts.accountCreatedSuccess: "Account creato con successo!",
    appTexts.passwordResetSuccess: "Password reimpostata con successo!",
    appTexts.error: "Errore",
    appTexts.pleaseEnterName: "Inserisci il tuo nome",
    appTexts.pleaseEnterEmail: "Inserisci la tua email",
    appTexts.pleaseEnterPassword: "Inserisci la tua password",
    appTexts.pleaseConfirmPassword: "Conferma la tua password",
    appTexts.passwordsDoNotMatch: "Le password non corrispondono",
    appTexts.agreeToTerms: "Accetta i termini e le condizioni",
    appTexts.countryCode: "Prefisso internazionale",
    appTexts.rememberMe: "Ricordami",
    appTexts.signIn: "Accedi",
    appTexts.fillRequiredFields: "Assicurati di compilare tutti i campi obbligatori (",
    appTexts.fieldsAccurately: ") \naccuratamente",
    appTexts.welcomeBack: "Bentornato!",
    appTexts.pleaseLogin: "Accedi al tuo account",
    appTexts.orContinueWith: "o continua con",
    appTexts.dontHaveAccount: "Non hai un account? ",
    appTexts.createOne: "Creane uno",
    appTexts.avatarUpdatedSuccess: "Avatar aggiornato con successo",
    appTexts.avatarUploadFailed: "Impossibile caricare l'avatar",
    appTexts.congratulation: "Congratulazioni!!!",
    appTexts.gotNextBeardCoin: "Hai ottenuto una nuova moneta barba!",
    appTexts.coinsCollectionAt: "La tua collezione di monete su ",
    appTexts.okGotIt: "Ok, ho capito!",
    appTexts.retry: "Riprova",
    appTexts.welcome: "Benvenuto",
    appTexts.scanQrCode: "Scansiona il tuo codice QR per ottenere una moneta barba",
    appTexts.personalId: "Questo è il tuo ID personale.",
    appTexts.scanQrInstruction: "Fai scansionare il tuo codice QR personale dal tuo barbiere di fiducia alla tua prossima visita e riceverai immediatamente un timbro digitale.",
    appTexts.beardCoinName: "La chiamiamo \"moneta barba\".",
    appTexts.beardCoins: "Monete Barba",
    appTexts.barbershops: "Barbieri",
    appTexts.shopping: "Shopping",
    appTexts.profile: "Profilo",
    appTexts.justNow: "Proprio ora",
    appTexts.mAgo: "m fa",
    appTexts.hAgo: "h fa",
    appTexts.dAgo: "g fa",
    appTexts.notifications: "Notifiche",
    appTexts.markAsRead: "Segna come letto",
    appTexts.noNotificationsYet: "Nessuna notifica ancora",
    appTexts.noMoreNotifications: "Nessuna altra notifica",
    appTexts.newText: "Nuovo",
    appTexts.earlier: "Precedente",
    appTexts.clickHereToParticipate: "Clicca qui per partecipare",
    appTexts.gift: "Regalo",
    appTexts.openingGiftDetails: "Apertura dettagli regalo...",
    appTexts.contest: "Concorso",
    appTexts.openingContestDetails: "Apertura dettagli concorso...",
    appTexts.reservation: "Prenotazione",
    appTexts.openingReservationDetails: "Apertura dettagli prenotazione...",
    appTexts.shareThisProfileVia: "Condividi questo profilo via",
    appTexts.linkCopiedToClipboard: "Link copiato negli appunti",
    appTexts.copy: "Copia",
    appTexts.sharingTo: "Condivisione su",
    appTexts.hallOfFame: "Hall of Fame",
    appTexts.currentContest: "Concorso Attuale",
    appTexts.previousWinners: "Vincitori precedenti",
    appTexts.loading: "Caricamento...",
    appTexts.failedToLoadData: "Impossibile caricare i dati",
    appTexts.noParticipantsYet: "Nessun partecipante ancora",
    appTexts.beFirstToJoin: "Sii il primo a partecipare al concorso!",
    appTexts.votes: "Voti",
    appTexts.totalVotes: "Voti Totali",
    appTexts.noPreviousContests: "Nessun concorso precedente ancora",
    appTexts.noWinnersYet: "Nessun vincitore ancora",
    appTexts.failedToLoadContest: "Impossibile caricare il concorso",
    appTexts.beardContest: "Concorso Barba",
    appTexts.participateInContest: "Partecipa al Concorso",
    appTexts.contestEndsIn: "Il concorso termina tra",
    appTexts.viewAll: "Vedi Tutto",
    appTexts.leaderBoard: "Classifica",
    appTexts.takeChanceToJoin: "Cogli l'occasione e sii il primo a partecipare.",
    appTexts.youAlreadyHave: "Hai già",
    appTexts.editPhoto: "Modifica Foto",
    appTexts.deletePhoto: "Elimina Foto",
    appTexts.changeDeletePhoto: "Cambia/elimina foto",
    appTexts.importantNote: "Nota Importante:",
    appTexts.changePhotoNote: "Se vuoi cambiare la tua foto o smettere di partecipare al concorso, puoi usare questa pagina.",
    appTexts.deletePhotoNote: "Dopo aver eliminato la tua foto, puoi caricarne una nuova. Altrimenti, sarai squalificato dal concorso.",
    appTexts.cancel: "Annulla",
    appTexts.delete: "Elimina",
    appTexts.contestDetails: "Dettagli Concorso",
    appTexts.failedToLoadDetails: "Impossibile caricare dettagli",
    appTexts.participants: "Partecipanti",
    appTexts.days: "Giorni",
    appTexts.hours: "Ore",
    appTexts.mins: "Min",
    appTexts.personalInfo: "Informazioni Personali",
    appTexts.myReservations: "Le Mie Prenotazioni",
    appTexts.privacySecurity: "Privacy e Sicurezza",
    appTexts.accountSettings: "Impostazioni Account",
    appTexts.helpSupport: "Aiuto e Supporto",
    appTexts.logout: "Esci",
    appTexts.all: "Tutto",
    appTexts.pending: "In Attesa",
    appTexts.confirmed: "Confermato",
    appTexts.failedToLoadReservations: "Impossibile caricare le prenotazioni",
    appTexts.noReservationsFound: "Nessuna prenotazione trovata",
    appTexts.withBarber: "con",
    appTexts.noDetailsFound: "Nessun dettaglio trovato",
    appTexts.yourCollection: "La Tua Collezione",
    appTexts.aboutUs: "Chi Siamo",
    appTexts.noDescriptionAvailable: "Nessuna descrizione disponibile.",
    appTexts.reviews: "Recensioni",
    appTexts.noReviewsYet: "Nessuna recensione ancora",
    appTexts.howToFindUs: "Come trovarci",
    appTexts.barbershopDetails: "Dettagli Barberia",
    appTexts.staff: "Staff:",
    appTexts.languages: "Lingue:",
    appTexts.payments: "Pagamenti:",
    appTexts.priceList: "Listino Prezzi",
    appTexts.noServicesListed: "Nessun servizio elencato",
    appTexts.openingHours: "Orari di Apertura",
    appTexts.noOpeningHoursListed: "Nessun orario elencato",
    appTexts.portfolio: "Portfolio",
    appTexts.seeAll: "Vedi Tutto",
    appTexts.members: "Membri",
    appTexts.closed: "Chiuso",
    appTexts.editProfile: "Modifica Profilo",
    appTexts.editYourProfile: "Modifica il tuo Profilo",
    appTexts.profilePicture: "Immagine del Profilo",
    appTexts.chooseProfilePicture: "Scegli Immagine Profilo",
    appTexts.takePhoto: "Scatta Foto",
    appTexts.chooseFromGallery: "Scegli dalla Galleria",
    appTexts.tapToChangeProfilePicture: "Tocca per cambiare la tua immagine del profilo.",
    appTexts.phoneNumber: "Numero di Telefono",
    appTexts.update: "Aggiorna",
    appTexts.accountUpdated: "Account Aggiornato",
    appTexts.manageYourAccount: "Gestisci il tuo Account",
    appTexts.changeLanguage: "Cambia Lingua",
    appTexts.deleteAccount: "Elimina Account",
    appTexts.deleteAccountQuestion: "Eliminare l'account?",
    appTexts.deleteAccountConfirmation: "Sei sicuro di voler confermare l'eliminazione del tuo account? Non potrai recuperarlo una volta eliminato. Per confermare digita Conferma.",
    appTexts.typeConfirmHere: "Digita \"Conferma\" qui",
    appTexts.accountDeleted: "Account Eliminato",
    appTexts.accountDeletedSuccess: "Il tuo account è stato eliminato con successo",
    appTexts.pleaseTypeConfirm: "Digita \"Conferma\" per eliminare il tuo account",
    appTexts.giveFeedback: "Dai Feedback",
    appTexts.howDidWeDo: "Come siamo andati?",
    appTexts.writeReview: "Scrivi una Recensione",
    appTexts.discard: "Scarta",
    appTexts.add: "Aggiungi",
    appTexts.success: "Successo",
    appTexts.reviewAddedSuccess: "Recensione aggiunta con successo",
    appTexts.reviewsFor: "Recensioni per",
    appTexts.customersFeedbackFor: "Feedback dei clienti per",
    appTexts.addReview: "Aggiungi Recensione",
    appTexts.ago: "fa",
  };

  static const Map<String, String> de = {
    appTexts.dashboard: "Dashboard",
    appTexts.pendingrequest: "Ausstehende Anfrage",
    appTexts.assigndriver: "Fahrer zuweisen",
    appTexts.availableDriver: "Verfügbarer Fahrer",
    appTexts.personalDetails: "Persönliche Daten",
    appTexts.navigate: "Navigieren",
    appTexts.notification: "Benachrichtigungen",
    appTexts.deliveryDetails: "Lieferdetails",
    appTexts.captionMedicalEquipment: "Medizinische Ausrüstung für Studenten",
    appTexts.customerName: "Kundenname",
    appTexts.pickupAddress: "Abholadresse",
    appTexts.deliveryAddress: "Lieferadresse",
    appTexts.deliveryDate: "Lieferdatum",
    appTexts.deliveryId: "Liefer-ID",
    appTexts.productDetails: "Produktdetails",
    appTexts.activity: "Aktivität",
    appTexts.message: "Nachricht",
    appTexts.inbox: "Posteingang",
    appTexts.account: "Konto",
    appTexts.name: "Name",
    appTexts.mail: "Mail",
    appTexts.mobile: "Handy",
    appTexts.address: "Adresse",
    appTexts.dateOfBirth: "Geburtsdatum",
    appTexts.nationality: "Nationalität",
    appTexts.email: "E-Mail",
    appTexts.paymentMethod: "Zahlungsmethode",
    appTexts.setting: "Einstellungen",
    appTexts.accountSettong: "Kontoeinstellung",
    appTexts.moreOption: "Mehr Optionen",
    appTexts.abouUs: "Über uns",
    appTexts.contactSupport: "Kontakt Support",
    appTexts.safetyPolicy: "Sicherheit & Richtlinie",
    appTexts.deliveryJobSupport: "Lieferung & Job Support",
    appTexts.appTechnicalHelp: "App & Technische Hilfe",
    appTexts.customerSuppoert: "Kundensupport",
    appTexts.requestForTruck: "LKW anfordern",
    appTexts.driverName: "Fahrername",
    appTexts.shipment: "Sendung",
    appTexts.subscriptionPlan: "Abonnementpläne",
    appTexts.signUp: "Anmelden",
    appTexts.companyName: "Firmenname",
    appTexts.companyMail: "Firmenmail",
    appTexts.companyLogo: "Firmenlogo",
    appTexts.uniqueCode: "Eindeutiger Code",
    appTexts.password: "Passwort",
    appTexts.confirmPassword: "Passwort bestätigen",
    appTexts.sparkDelivery: "Spark Lieferung",
    appTexts.addDriver: "Fahrer hinzufügen",
    appTexts.addDispatcher: "Dispatcher hinzufügen",
    appTexts.driverDetails: "Fahrerdetails",
    appTexts.onboardingTitle1: "Entdecke Barbershops in deiner Nähe",
    appTexts.onboardingDesc1: "Finde die besten Barbershops in deiner Umgebung – mit echten Bewertungen, die dir helfen, den perfekten Schnitt und den richtigen Barbier zu wählen. Entdecke Barbiere, die zu deinem Stil, Budget und deinen Vorlieben passen.",
    appTexts.onboardingTitle2: "Mach mit beim Online-Bartwettbewerb",
    appTexts.onboardingDesc2: "Zeig deinen Bart in unserer exklusiven Community, nimm am Online-Wettbewerb teil und gewinne tolle Preise. Hall of Fame inklusive!",
    appTexts.onboardingTitle3: "Sammle exklusive Beardcoins",
    appTexts.onboardingDesc3: "Verdiene digitale Stempel – unsere Beardcoins! Sammle Treuepunkte und schalte spezielle Vorteile für echte Bartliebhaber frei.",
    appTexts.onboardingTitle4: "Steigere die Sichtbarkeit deines Shops",
    appTexts.onboardingDesc4: "Barbershop-Besitzer registrieren ihren Shop, präsentieren wichtige Infos und werden entdeckt – alles ohne eigene Website.",
    appTexts.onboardingTitle5: "100% Digital, Null Papier",
    appTexts.onboardingDesc5: "Keine gedruckten Stempelkarten mehr. Vergib digitale Belohnungen, lege eigene Rabatte fest und überrasche Kunden intelligenter als je zuvor.",
    appTexts.skip: "Überspringen",
    appTexts.next: "Weiter",
    appTexts.tellUsAboutYourself: "Erzähl uns von dir",
    appTexts.chooseToContinue: "Wähle um fortzufahren",
    appTexts.beardfriend: "Bartfreund",
    appTexts.beardfriendDesc: "(Nur für Mitglieder)",
    appTexts.barbershop: "Barbershop",
    appTexts.barbershopDesc: "(Nur für Besitzer)",
    appTexts.cookieSettings: "Cookie-Einstellungen",
    appTexts.cookiePolicy: "Wir verwenden Cookies und ähnliche Technologien, um Inhalte zu personalisieren, Anzeigen anzupassen und zu messen und ein besseres Erlebnis zu bieten. Durch Klicken auf Akzeptieren stimmen Sie diesem zu, wie in unserer ",
    appTexts.cookiePolicyLink: "Cookie-Richtlinie",
    appTexts.onlyEssentials: "Nur notwendige",
    appTexts.changeCookieSettings: "Cookie-Einstellungen ändern",
    appTexts.acceptAll: "Alle akzeptieren",
    appTexts.createAccount: "Konto erstellen",
    appTexts.pleaseSignup: "Bitte registrieren Sie sich für Ihr Konto",
    appTexts.username: "Benutzername",
    appTexts.emailAddress: "E-Mail-Adresse",
    appTexts.dob: "TT/MM/JJJJ",
    appTexts.confirmPass: "Passwort bestätigen",
    appTexts.alreadyHaveAccount: "Haben Sie bereits ein Konto? ",
    appTexts.login: "Anmelden",
    appTexts.gdprTerms: "DSGVO und Allgemeine Geschäftsbedingungen",
    appTexts.agreePrivacyPolicy: "Ich stimme zu & akzeptiere ",
    appTexts.privacyPolicy: "Datenschutzrichtlinie",
    appTexts.agreeTerms: "Ich stimme zu & akzeptiere ",
    appTexts.generalTerms: "Allgemeine Geschäftsbedingungen",
    appTexts.termsHelper: "Stellen Sie sicher, dass Sie unsere Allgemeinen Geschäftsbedingungen gelesen haben, bevor Sie mit der App fortfahren",
    appTexts.continueText: "Weiter",
    appTexts.otp: "OTP",
    appTexts.otpSent: "Wir haben den Bestätigungscode an Ihre\nE-Mail-Adresse gesendet",
    appTexts.didntGetCode: "Code nicht erhalten? ",
    appTexts.resendIt: "Erneut senden",
    appTexts.forgotPassword: "Passwort vergessen?",
    appTexts.typeEmailAddress: "Bitte geben Sie Ihre E-Mail-Adresse ein",
    appTexts.resetPassword: "Passwort zurücksetzen",
    appTexts.rememberPassword: "Passwort merken? ",
    appTexts.newPassword: "Neues Passwort",
    appTexts.confirmPasswordText: "Passwort bestätigen",
    appTexts.accountCreatedSuccess: "Konto erfolgreich erstellt!",
    appTexts.passwordResetSuccess: "Passwort erfolgreich zurückgesetzt!",
    appTexts.error: "Fehler",
    appTexts.pleaseEnterName: "Bitte geben Sie Ihren Namen ein",
    appTexts.pleaseEnterEmail: "Bitte geben Sie Ihre E-Mail-Adresse ein",
    appTexts.pleaseEnterPassword: "Bitte geben Sie Ihr Passwort ein",
    appTexts.pleaseConfirmPassword: "Bitte bestätigen Sie Ihr Passwort",
    appTexts.passwordsDoNotMatch: "Passwörter stimmen nicht überein",
    appTexts.agreeToTerms: "Bitte akzeptieren Sie die Geschäftsbedingungen",
    appTexts.countryCode: "Ländercode",
    appTexts.rememberMe: "Angemeldet bleiben",
    appTexts.signIn: "Anmelden",
    appTexts.fillRequiredFields: "Bitte füllen Sie alle erforderlichen Felder (",
    appTexts.fieldsAccurately: ") \nkorrekt aus",
    appTexts.welcomeBack: "Willkommen zurück!",
    appTexts.pleaseLogin: "Bitte loggen Sie sich in Ihr Konto ein",
    appTexts.orContinueWith: "oder weiter mit",
    appTexts.dontHaveAccount: "Kein Konto? ",
    appTexts.createOne: "Eines erstellen",
    appTexts.avatarUpdatedSuccess: "Avatar erfolgreich aktualisiert",
    appTexts.avatarUploadFailed: "Avatar konnte nicht hochgeladen werden",
    appTexts.congratulation: "Herzlichen Glückwunsch!!!",
    appTexts.gotNextBeardCoin: "Sie haben eine neue Bart-Münze erhalten!",
    appTexts.coinsCollectionAt: "Ihre Münzsammlung bei ",
    appTexts.okGotIt: "Ok, verstanden!",
    appTexts.retry: "Wiederholen",
    appTexts.welcome: "Willkommen",
    appTexts.scanQrCode: "Scannen Sie Ihren QR-Code, um eine Bart-Münze zu erhalten",
    appTexts.personalId: "Dies ist Ihre persönliche ID.",
    appTexts.scanQrInstruction: "Lassen Sie Ihren persönlichen QR-Code bei Ihrem nächsten Besuch von Ihrem Friseur scannen und Sie erhalten sofort einen digitalen Stempel.",
    appTexts.beardCoinName: "Wir nennen es \"Bart-Münze\".",
    appTexts.beardCoins: "Bartmünzen",
    appTexts.barbershops: "Friseursalons",
    appTexts.shopping: "Einkaufen",
    appTexts.profile: "Profil",
    appTexts.justNow: "Gerade eben",
    appTexts.mAgo: "m her",
    appTexts.hAgo: "h her",
    appTexts.dAgo: "t her",
    appTexts.notifications: "Benachrichtigungen",
    appTexts.markAsRead: "Als gelesen markieren",
    appTexts.noNotificationsYet: "Noch keine Benachrichtigungen",
    appTexts.noMoreNotifications: "Keine weiteren Benachrichtigungen",
    appTexts.newText: "Neu",
    appTexts.earlier: "Früher",
    appTexts.clickHereToParticipate: "Hier klicken um teilzunehmen",
    appTexts.gift: "Geschenk",
    appTexts.openingGiftDetails: "Geschenkdetails öffnen...",
    appTexts.contest: "Wettbewerb",
    appTexts.openingContestDetails: "Wettbewerbsdetails öffnen...",
    appTexts.reservation: "Reservierung",
    appTexts.openingReservationDetails: "Reservierungsdetails öffnen...",
    appTexts.shareThisProfileVia: "Profil teilen via",
    appTexts.linkCopiedToClipboard: "Link in Zwischenablage kopiert",
    appTexts.copy: "Kopieren",
    appTexts.sharingTo: "Teilen auf",
    appTexts.hallOfFame: "Ruhmeshalle",
    appTexts.currentContest: "Aktueller Wettbewerb",
    appTexts.previousWinners: "Frühere Gewinner",
    appTexts.loading: "Laden...",
    appTexts.failedToLoadData: "Daten konnten nicht geladen werden",
    appTexts.noParticipantsYet: "Noch keine Teilnehmer",
    appTexts.beFirstToJoin: "Sei der Erste, der am Wettbewerb teilnimmt!",
    appTexts.votes: "Stimmen",
    appTexts.totalVotes: "Gesamtstimmen",
    appTexts.noPreviousContests: "Noch keine früheren Wettbewerbe",
    appTexts.noWinnersYet: "Noch keine Gewinner",
    appTexts.failedToLoadContest: "Wettbewerb konnte nicht geladen werden",
    appTexts.beardContest: "Bart-Wettbewerb",
    appTexts.participateInContest: "Am Wettbewerb teilnehmen",
    appTexts.contestEndsIn: "Wettbewerb endet in",
    appTexts.viewAll: "Alle anzeigen",
    appTexts.leaderBoard: "Bestenliste",
    appTexts.takeChanceToJoin: "Nutze die Chance und mach als Erster mit.",
    appTexts.youAlreadyHave: "Du hast bereits",
    appTexts.editPhoto: "Foto bearbeiten",
    appTexts.deletePhoto: "Foto löschen",
    appTexts.changeDeletePhoto: "Foto ändern/löschen",
    appTexts.importantNote: "Wichtiger Hinweis:",
    appTexts.changePhotoNote: "Wenn Sie Ihr Foto ändern oder nicht mehr am Wettbewerb teilnehmen möchten, können Sie diese Seite nutzen.",
    appTexts.deletePhotoNote: "Nach dem Löschen Ihres Fotos können Sie ein neues hochladen. Andernfalls werden Sie vom Wettbewerb disqualifiziert.",
    appTexts.cancel: "Abbrechen",
    appTexts.delete: "Löschen",
    appTexts.contestDetails: "Wettbewerbsdetails",
    appTexts.failedToLoadDetails: "Details konnten nicht geladen werden",
    appTexts.participants: "Teilnehmer",
    appTexts.days: "Tage",
    appTexts.hours: "Stunden",
    appTexts.mins: "Min",
    appTexts.personalInfo: "Persönliche Daten",
    appTexts.myReservations: "Meine Reservierungen",
    appTexts.privacySecurity: "Datenschutz & Sicherheit",
    appTexts.accountSettings: "Kontoeinstellungen",
    appTexts.helpSupport: "Hilfe & Support",
    appTexts.logout: "Abmelden",
    appTexts.all: "Alle",
    appTexts.pending: "Ausstehend",
    appTexts.confirmed: "Bestätigt",
    appTexts.failedToLoadReservations: "Reservierungen konnten nicht geladen werden",
    appTexts.noReservationsFound: "Keine Reservierungen gefunden",
    appTexts.withBarber: "mit",
    appTexts.noDetailsFound: "Keine Details gefunden",
    appTexts.yourCollection: "Deine Sammlung",
    appTexts.aboutUs: "Über uns",
    appTexts.noDescriptionAvailable: "Keine Beschreibung verfügbar.",
    appTexts.reviews: "Bewertungen",
    appTexts.noReviewsYet: "Noch keine Bewertungen",
    appTexts.howToFindUs: "So finden Sie uns",
    appTexts.barbershopDetails: "Barbershop Details",
    appTexts.staff: "Personal:",
    appTexts.languages: "Sprachen:",
    appTexts.payments: "Zahlungen:",
    appTexts.priceList: "Preisliste",
    appTexts.noServicesListed: "Keine Dienstleistungen aufgeführt",
    appTexts.openingHours: "Öffnungszeiten",
    appTexts.noOpeningHoursListed: "Keine Öffnungszeiten aufgeführt",
    appTexts.portfolio: "Portfolio",
    appTexts.seeAll: "Alle anzeigen",
    appTexts.members: "Mitglieder",
    appTexts.closed: "Geschlossen",
    appTexts.editProfile: "Profil bearbeiten",
    appTexts.editYourProfile: "Bearbeite dein Profil",
    appTexts.profilePicture: "Profilbild",
    appTexts.chooseProfilePicture: "Profilbild auswählen",
    appTexts.takePhoto: "Foto aufnehmen",
    appTexts.chooseFromGallery: "Aus Galerie auswählen",
    appTexts.tapToChangeProfilePicture: "Tippen Sie, um Ihr Profilbild zu ändern.",
    appTexts.phoneNumber: "Telefonnummer",
    appTexts.update: "Aktualisieren",
    appTexts.accountUpdated: "Konto aktualisiert",
    appTexts.manageYourAccount: "Konto verwalten",
    appTexts.changeLanguage: "Sprache ändern",
    appTexts.deleteAccount: "Konto löschen",
    appTexts.deleteAccountQuestion: "Konto löschen?",
    appTexts.deleteAccountConfirmation: "Sind Sie sicher, dass Sie Ihr Konto löschen möchten? Sie können es nicht wiederherstellen, sobald es gelöscht ist. Zur Bestätigung geben Sie bitte Bestätigen ein.",
    appTexts.typeConfirmHere: "Geben Sie hier \"Bestätigen\" ein",
    appTexts.accountDeleted: "Konto gelöscht",
    appTexts.accountDeletedSuccess: "Ihr Konto wurde erfolgreich gelöscht",
    appTexts.pleaseTypeConfirm: "Bitte geben Sie \"Bestätigen\" ein, um Ihr Konto zu löschen",
    appTexts.giveFeedback: "Feedback geben",
    appTexts.howDidWeDo: "Wie haben wir abgeschnitten?",
    appTexts.writeReview: "Bewertung schreiben",
    appTexts.discard: "Verwerfen",
    appTexts.add: "Hinzufügen",
    appTexts.success: "Erfolg",
    appTexts.reviewAddedSuccess: "Bewertung erfolgreich hinzugefügt",
    appTexts.reviewsFor: "Bewertungen für",
    appTexts.customersFeedbackFor: "Kundenfeedback für",
    appTexts.addReview: "Bewertung hinzufügen",
    appTexts.ago: "vor",
  };
}
